name: astrbot_plugin_sekairanking_predata # 插件唯一识别名，以 astrbot_plugin_ 前缀开头
display_name: PJSK Rankline Predict # 用于展示的名字，可以是方便人类阅读的名字（需要版本 >= v4.5.0，低版本不会报错，请放心填写）
desc: |
  PJSK国服榜线预测。支持以下cnskp指令：
  1. cnskp → 截图/simple页面
  2. cnskp event[数字] → 截图/event/[数字]页面
  3. cnskp event[数字] PGAI → 截图/index/event/[数字]页面
  4. cnskp t[数字] → 截图指定chart-[数字]模块（数字限50/100/200/300/400/500/1000/2000/3000/4000/5000/10000） # 插件简短描述
version: v1.3.0 # 插件版本号。格式：v1.1.1 或者 v1.1
author: StreamOfAutumn # 作者
repo: https://github.com/HomnaMisuzu/astrbot_plugin_sekairanking_predata # 插件的仓库地址
triggers:  # 指令触发规则（AstrBot核心识别逻辑）
  - type: command
    keywords: ["cnskp"]  # 触发关键词
priority: 5  # 插件优先级（0-10）
enabled: true  # 默认启用